### ISSUE TITLE
Tekst wijzigen

### ISSUE THREAD

**Issue by jgroenen** [codefornl/slack-greet#1]
Doel: de community introduceren, de rol van slack daarin, en wat er actueel is

**Comment by jgroenen** [comment]
Voorstel Ivonne:

---

In dit kanaal vind je een korte samenvatting van de belangrijkste informatie die nodig is een vliegende start te maken :airplane_departure:

Code for NL is de Nederlandse community van developers en designers die samenwerken aan een open, eerlijke, en inclusieve digitale overheid en samenleving. Ons doel is een sterke Nederlandse public tech beweging waar vanuit publieke waarden en belangen gewerkt wordt aan de digitale transformatie van overheid en maatschappij. Code for NL is governing partner van het internationale Code for All netwerk. Voor meer informatie, zie www.codefor.nl

# Wat moet je weten voor je begint?

- Op deze Slack omgeving geldt de Code for NL gedragscode (https://github.com/codefornl/gedragscode). Voor vragen en opmerkingen is het bestuur te vinden op #bestuur-publiek.
- Code for NL geloof in een sterke public tech beweging die werkt vanuit Community Principles (https://github.com/codefornl/community-principes)
- Wij onderschrijven de Standard for Public Code (https://standard.publiccode.net/) als uitgangspunt in open projecten
- Code for NL is een omgeving waar 'doen' en 'open' centraal staat. Marketing en commerciële aanbiedingen worden niet op prijs gesteld.

# Wat kun je hier allemaal vinden?

Aan de ontwikkeling van open Nederlandse digitale public tech wordt in meerdere kanalen gewerkt:

#publiccode - gesprek over de Standard for Public Code en doorontwikkeling daarvan

#developer-overheid-nl - gedeeld kanaal met de community achter developer.overheid.nl

#nl-design-system - het nieuwe Nederlandse Design System wordt besproken en doorontwikkeld

#codefornl-codeforall-shared - gedeeld kanaal met de wereldwijde Code for All community

## Het Ministerie van VWS werkt in alle openheid aan de ontwikkeling van een covid 19 notificatie app, in o.a. deze kanalen:

#notificatie-app - algemene updates, gesprekken over de gekozen technologische richting

#notificatie-app-design - een van de specifieke sub kanalen, gericht op de UX van de app

#notificatie-app-hulpvragen - een overzicht van specifieke issues waar je kunt meewerken

#notificatie-app-architectuur - discussie over de technische keuzes

## Interessante community projecten zijn op dit moment:

#corona-helpradar - project waarin met LOT-C wordt samengewerkt om hulpvragen in kaart te brengen Voor meer info https://www.codefor.nl

#lockdown - internationale samenwerking rondom ontsluiting wereldwijde lockdown informatie

## Corona gerelateerde kanalen:

#corona - startpunt voor het gesprek, vragen en ideeen rondom corona ontwikkelingen

#corona-data - databronnen in kaart

#corona-brainstorm -  dump voor leuke, inspirerende nieuwe inzichten en ideeen

#influenzanet-codefornl-shared - gedeeld kanaal met de EU influenzanet community (met RIVM)

Gebruik vooral de channel browser om een van de momenteel 67 kanalen te vinden.

Nogmaals fijn dat je er bent!

**Comment by ivonnedings** [comment]
Nog een wijzigingsvoorstel bij "wat kun je hier allemaal vinden":

Aan de ontwikkeling van open Nederlandse digitale public tech wordt in meerdere kanalen gewerkt:

#algemeen - startplek voor algemene (hulp)vragen en informatie
#publiccode - gesprek over de Standard for Public Code en doorontwikkeling daarvan

**Comment by JolandaVerhoef** [comment]
> Ons doel is een sterke Nederlandse public tech beweging waar vanuit publieke waarden en belangen gewerkt wordt aan de digitale transformatie van overheid en maatschappij.

Moeilijk te lezen passieve zin, misschien wijzigen naar:
Ons doel is een sterke Nederlandse public tech beweging die vanuit publieke waarden en belangen werkt aan de digitale transformatie van overheid en maatschappij.

**Comment by JolandaVerhoef** [comment]
> Code for NL geloof in een sterke public tech beweging die werkt vanuit Community Principles (https://github.com/codefornl/community-principes)

typo: `geloof` moet zijn `gelooft`

Daarnaast hebben sommige zinnen in deze opsomming een punt, anderen niet.

**Comment by JolandaVerhoef** [comment]
Misschien kunnen we alvast kanalen voor android & iOS toevoegen, in de notificatie-app space. Dus `notificatie-app-android` en `notificatie-app-ios`. Mogelijk kunnen we hier shared channels van maken met de betreffende communities in Nederland (bv voor Android de DutchAug community)

Dat scheelt weer een aanpassing over een paar dagen.

**Comment by jgroenen** [comment]
Overgenomen uit Slack (EvS): "Aantal gedachten op een rij adhv het laatste tekstvoorstel. Dat heeft pluspunten maar ook minpunten. Psychologisch is circa 4-8 punten die je 'moet' weten in deze tekst ideaal. Als het te veel wordt gaan mensen het overslaan, worden ze overspoeld. Je wil in die 4-8 punten dus vermelden hoe men zich verder kan informeren, zodat iemand die voor een specifiek onderwerp komt de juiste 'route'/processtroom kiest naar waar hij/zij die info kan vinden.

Kies voor specifieke termen die duidelijk het doel aangeven. Bijv. governing partner is niet zo'n specifieke term. Wat betekent dit in deze context? Het is jargon wat velen niet zullen begrijpen.

De links vind ik erg sterk, daar kun je dus zelf verder lezen zodra je hier tijd voor wilt maken.

Ik zou de volgorde evt wijzigen? Mijn assumptie is nu dat veel mensen eerst info willen over VWS (dat zou je kunnen testen aan aantal echte nieuwkomers) en dus een beetje verdwalen als je eerst veel vertelt over info waar zij niet direct voor komen. Koppeling goed maken met wat Code for all in het algemeen is en waarom/hoe/etc zij met VWS verbonden zijn.

Vind ook de laatste zin heel sterk, "Gebruik de channel browser om één van de 67 andere kanalen te vinden"."
